### ISSUE TITLE
surface form for SPMe

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1207]
At the moment if you pass the option `{"surface form":"differential"}` or `{"surface form": "algebraic"}` to SPMe nothing happens. SPMe always uses `pybamm.electrolyte_conductivity.Composite`. 

We should either raise an `OptionError` or add the relevant surface models for SPMe

**Comment by brosaplanella** [comment]
I tried implementing this in #884 in case it was a quick fix but I am getting errors for both models (full and leading-order). For the moment I set it to throw a `NotImplementedError` so if that is enough we may close this issue once #884 is merged.

Otherwise, if we want to implement the model, we need to derive the appropriate surface form for `Composite`. Is there any reference on this kind of formulation?

**Comment by tinosulzer** [comment]
There is my thesis, if you are feeling brave, but I wouldn't go down that route. In theory the leading order form should work though. What was the error?

**Comment by brosaplanella** [comment]
The differential works but the algebraic doesn't. Here is the error:
```
======================================================================
ERROR: test_surface_form_algebraic (__main__.TestSPMe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ferranbrosa/PyBaMM/tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_spme.py", line 119, in test_surface_form_algebraic
    model.check_well_posedness()
  File "/home/ferranbrosa/PyBaMM/pybamm/models/base_model.py", line 377, in check_well_posedness
    self.check_well_determined(post_discretisation)
  File "/home/ferranbrosa/PyBaMM/pybamm/models/base_model.py", line 469, in check_well_determined
    raise pybamm.ModelError("model is overdetermined (repeated keys)")
pybamm.expression_tree.exceptions.ModelError: model is overdetermined (repeated keys)

----------------------------------------------------------------------
```
