### ISSUE TITLE
Add docs and example for plot_voltage_components

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1605]
Add documentation for `pybamm.plot_voltage_components` and either add a new example showing this or add this plot to an existing example

**Comment by Saransh-cpp** [comment]
Can I take this up? if no one is working on it.

**Comment by rtimms** [comment]
Yep, thanks!

**Comment by nickbrady** [comment]
I know this issue is closed, but if I follow the code outlined in [Tutorial 3: Basic Plotting](https://docs.pybamm.org/en/latest/source/examples/notebooks/getting_started/tutorial-3-basic-plotting.html) `sim.plot_voltage_components()` produces the error: AttributeError: 'Simulation' object has no attribute 'plot_voltage_components'

MWE
```python
import pybamm

model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])

sim.plot_voltage_components()
```

**Comment by agriyakhetarpal** [comment]
Hi, @nickbrady – I tried to reproduce the MWE with the latest changes from the `develop` branch and also on the latest release (v23.9), but I cannot reproduce the issue. The code executes without errors for me and produces the desired plot with all of the overpotentials. Could you please re-install PyBaMM or try it within a fresh environment? If it doesn't work, I would suggest creating a new issue for this.

**Comment by nickbrady** [comment]
I reinstalled pybamm today 

pybamm.__version__ = '24.1'

and I get the same error. I am getting errors when going through other snippets of code from the Examples section of the documentation as well.
