### ISSUE TITLE
Indefinite integral

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#175]
Implementing something like F(x) = int_0^x f(x) dx (a bit tricky with finite volumes, dealing with all four cases of whether the integrand / resulting integral is to be evaluated on the nodes or on the edges. 

Might be easier to implement as solving an ODE in x: dF/dx = f(x).

**Comment by Scottmar93** [comment]
I think for first version we should run with just adding an extra post_process ODE as it shouldn't be too hard to implement. 

We could at a later stage just add a front end symbol for an indenfinite integral but under the hood we actually just solve the equivalent ODE.

**Comment by Scottmar93** [comment]
Following discussions on the possible node/edges cases we have decided to implement indefinite integral so that it always evaluates to nodes (therefore treating it in the same manner as the variables in the model). To extract an edge value the NodeToEdge function must be used just like any other variables.
