### ISSUE TITLE
[Bug]: Equations not displaying properly in docs for 1D submesh

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/PyBaMM#2226]
### PyBaMM Version

22.7

### Python Version

3.9

### Describe the bug

https://pybamm.readthedocs.io/en/latest/source/meshes/one_dimensional_submeshes.html

### Steps to Reproduce

https://pybamm.readthedocs.io/en/latest/source/meshes/one_dimensional_submeshes.html

**Comment by eagunn** [comment]
Contributing a comment rather than a fix. I'm not set up to build and test. I was just cruising through the issues deciding if this was a project where I might be able to make contributions in the future. But, since I think I've figured out what is wrong with the PyDoc comments, I thought I would leave a note here to possibly make the eventual fix faster for the next in line. 

I looks as if the documentation for these classes is stuck between two approaches to documenting exponents of e. See [https://tex.stackexchange.com/questions/254785/e-vs-exp-in-display-mode](https://tex.stackexchange.com/questions/254785/e-vs-exp-in-display-mode) for a helpful discussion of the two approaches.

Specifically, I believe the raw equation in the Pydoc:
`x_{k} = (b-a) + \\frac{\\exp{\\alpha k / N} - 1}{\\exp{\\alpha} - 1} + a,`
should be more like
`x_{k} = (b-a) + \\frac{\\exp(\\alpha k / N) - 1}{\\exp(\\alpha} - 1) + a,`

That is, the Tex operator \exp is to be followed by the expression in parentheses, not curly brackets.

**Comment by dikwickley** [comment]
@tinosulzer @TomTranter i would like to work on this issue.

**Comment by tinosulzer** [comment]
Let us know if you need help

**Comment by dikwickley** [comment]
are these the equations that are not being displayed correctly?
<img width="855" alt="image" src="https://user-images.githubusercontent.com/31622972/215015642-72786590-d0a9-44e2-aafc-9b2bc61aada6.png">
from what I can understand, the exponent part is displayed incorrectly.

and if yes, can you point me toward any source material that shows how they should actually look like?

**Comment by dikwickley** [comment]
@tinosulzer i have created a PR, please review it. thanks
