### ISSUE TITLE
`pybamm.citations.register` does not work on Google Colab

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#2543]
I have been using PyBaMM for most of 2022 with no issues, but since Google Colab was updated to Python 3.8, I have not been able to run any simulations. 

I have tried the following fixes to no avail:
1. Installed PyBaMM on Colab with `pip install git+https://github.com/pybamm-team/PyBaMM@develop` as suggested by @Saransh-cpp 
- Allows installing/importing  pybamm, but throws an error when defining the model or the parameter_values
- `model = pybamm.lithium_ion.DFN(options={"thermal":"lumped"})` or `parameter_values = pybamm.ParameterValues('Chen2020')`
- Error1: KeyError: 'Not a bibtex citation or known citation: Ai2019'
- Error2: KeyError: 'Not a bibtex citation or known citation: Chen2020'
2. Attempted installation on my local environment (desktop) with `pip install pybamm` 
- Throws an ERROR during installation 
- ERROR: PluginNotFound: plugin pybtex.database.input.bibtex not found
3. Installed PyBaMM on my local environment (desktop) with `pip install git+https://github.com/pybamm-team/PyBaMM@develop`
- Allows installation but throws an ERROR during `import pybamm`
- ERROR: PluginNotFound: plugin pybtex.database.input.bibtex not found

Any other suggestions?

_Originally posted by @renatorod in https://github.com/pybamm-team/PyBaMM/issues/2524#issuecomment-1345971134_

**Comment by tinosulzer** [comment]
Since this is causing so many problems and not being to print citations is not a huge problem, I think we should just have general try/except blocks around all the places where entry points can cause errors where the error gets saved but not raised, and then raise the error only if the user tries to call `print_citations`

Also once fixed let's release this as a patch 22.11.1 to main
