### ISSUE TITLE
`inspect` causing big performance regression

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2908]
<img width="1008" alt="Screenshot 2023-04-30 at 1 17 59 PM" src="https://user-images.githubusercontent.com/20817509/235366967-24401e33-17b2-47af-9b71-767c4afccae7.png">
<img width="1246" alt="Screenshot 2023-04-30 at 1 18 42 PM" src="https://user-images.githubusercontent.com/20817509/235366978-602e5d28-1aa7-4d53-b68c-2b99e13494ba.png">

This is due to #2862 

@agriyakhetarpal can you look into a way to make this faster? Otherwise we should revert, it's not worth the functionality gain

**Comment by tinosulzer** [comment]
This is a huge performance hit in some cases (e.g. repeated solving of the SPM is not 10x slower) so we should fix immediately and make a 23.4.1 release
<img width="1251" alt="Screenshot 2023-04-30 at 1 23 01 PM" src="https://user-images.githubusercontent.com/20817509/235367174-c1bed33d-b8c9-48a3-bcdf-9da7ce7c8fbd.png">

Maybe this helps https://stackoverflow.com/questions/17407119/python-inspect-stack-is-slow

**Comment by tinosulzer** [comment]
Also weird that the benchmarks never caught this, are they working now @Saransh-cpp ?

**Comment by agriyakhetarpal** [comment]
Since this is immediate I am happy to revert — though I will get back on this and try some other faster implementation in the next week, wasn't aware of such a potential slowdown 😅 Where can I run the above profiler?

**Comment by tinosulzer** [comment]
It's snakeviz, you can pip install then run in `ipython` terminal 
```
> %load_ext snakeviz
> %snakeviz function_to_profile()
```

**Comment by tinosulzer** [comment]
Potential solutions are:
- find a faster implementation of doing the same thing
- use some form of caching so this is only calculated once per `register` call
- add tagging manually as an input to the `register` function
- remove altogether

**Comment by agriyakhetarpal** [comment]
I agree with removing altogether and releasing a patch for now.

- We can indeed explore a caching option, albeit will some overhead still remain when a model is called and its citation is registered for the first time when running an experiment? In that case a faster `inspect.stack()` implementation altogether would be better or by modifying all `__call__` methods with a metaclass

- Preserving a `dict` of models mapped to their citations hardcoded manually is also a solution 

I am just figuring out some end-semester assignments and submissions so it will take me a few days to try these ways. Please go ahead and reopen #1182 for the time being

**Comment by Saransh-cpp** [comment]
> Also weird that the benchmarks never caught this, are they working now @Saransh-cpp ?

The benchmarks were indeed failing on develop, but the benchmark workflow was fixed after the `inspect` PR was merged. Also, benchmarks only run on `push` and would not run on PRs from forks (I am not sure why?).

**Comment by tinosulzer** [comment]
We should allow it to run on PRs from forks

**Comment by agriyakhetarpal** [comment]
@tinosulzer, I tried to profile a faster implementation (it turns out that using `inspect.currentframe` is miles faster than `inspect.stack` because it does not create a stack trace). However, I am not sure if I'm correctly interpreting the visualisations I get from `snakeviz` – here's what I am running:

```python
# In the ipython shell
import pybamm
%load_ext snakeviz
%snakeviz pybamm.lithium_ion.SPMe()
```
## Before
![image](https://user-images.githubusercontent.com/74401230/236516319-2f4daaa1-69db-4802-8813-4ae906728118.png)

and the results for `pybamm.citations.register()`, and for `_caller_name()` that gets called internally by `register()`
| ncalls | tottime | percall | cumtime  | percall  | filename:lineno(function)     |
|--------|---------|---------|----------|----------|-------------------------------|
| 1 | 7.4e-06 | 7.4e-06 | 0.03022 | 0.03022 | citations.py:109(register)    |
| 1 | 9.9e-06 | 9.9e-06 | 0.03021  | 0.03021  | citations.py:61(_caller_name) |

## Now

![image](https://user-images.githubusercontent.com/74401230/236516433-dc7122a7-7a28-4d32-a2f4-513641d26984.png)

| ncalls | tottime | percall | cumtime  | percall  | filename:lineno(function)     |
|--------|---------|---------|----------|----------|-------------------------------|
| 1 | 6.4e-06 | 6.4e-06 | 1.35e-05 | 1.35e-05 | citations.py:111(register)    |
| 1 | 4.2e-06 | 4.2e-06 | 6.4e-06   | 6.4e-06    | citations.py:61(_caller_name) |

which seems to be at least 2000x faster if we compare cumulative times (the earlier takes ~27% of the time taken to call SPM, which then dropped down to 0.02% in the latter); assuming I am reading the results right. This can be sped up even more if we use `sys._getframe` instead, but using internal functions from `sys` is generally discouraged. 

Could you perhaps write the code for a longer and very complex PyBaMM experiment that I can try to profile (such as the ones running behind your screenshots above) just to see if the results are scaling properly and do not cause any performance regressions?

**Comment by tinosulzer** [comment]
```python
> import pybamm
> %load_ext snakeviz
> %snakeviz model = pybamm.lithium_ion.DFN()
> sim = pybamm.Simulation(model) # should be very fast, no need to profile
> %snakeviz sim.solve([0,3600]) 
> %snaleviz sim.solve([0,3600])
```
The final solve is repeated twice because several things get cached the first time. Ideally, the second time, almost all the time should be spent in the `_integrate` method of the solver.

Also repeat the whole thing with `pybamm.lithium_ion.SPM()`, which is faster and therefore any overheads are a larger percentage of the total runtime.

It looks like using `inspect.currentframe` will be a sufficient fix.

**Comment by agriyakhetarpal** [comment]
Thanks; for initialising the DFN model, the performance hit with `register` is 0.01–0.03%. With `sim.solve([0, 3600])`, the mean comes out to be around 0.02%, and on running `sim.solve([0, 3600])` again, it comes out as about 0.15% (15 ncalls). I repeated the process for ten iterations (for SPM as well below) to make sure I'm not receiving any statistical outliers and that the behaviour was okay. 

The second time, `_integrate` always takes ~94–95% of the total time, which, as you said, should be ideal:

![image](https://user-images.githubusercontent.com/74401230/236608135-47ebf694-dc64-44d3-8bd5-1767d3cafc4c.png)

Similar results arise for the SPM model: the performance hit for `register` is 0.01–0.03%, though on the second iteration of `sim.solve([0, 3600])`, it shoots up to 1.5–1.6% (14 ncalls). Since things are cached, `_integrate` uses 88% of the total time:

![image](https://user-images.githubusercontent.com/74401230/236608570-ac70cfad-1d52-4147-b831-d7358d32de09.png)

which means registering citations for the SPM model impacts it just slightly more than doing so for the DFN model – is this performance reasonable enough to open a PR, or should I try to improve upon this more?

**Comment by tinosulzer** [comment]
Sorry I forgot to reply to previous discussion. The speedup is great, but it's surprising that it's being called 14 times on the second solve. Can you find a way to cache the citation tags?

**Comment by agriyakhetarpal** [comment]
Yes sure, I'll give that a try and convert that to a draft – would you suggest using `functools` or would some basic caching with a dictionary suffice? If we're aiming for a best-case scenario, the time taken to read the citation from it should hopefully be negligible compared to registering it

**Comment by tinosulzer** [comment]
Either is fine

**Comment by agriyakhetarpal** [comment]
Just using `@cache` from `functools` (under the assumption that a built-in way would be better than writing a custom cache) and without any other changes halves the total time taken to about ~0.87% (averaged out across 10 times) on the second time a simulation of the SPM model is solved with `sim.solve([0, 3600])`, and this value keeps getting smaller in later iterations, but the number of ncalls remains the same due to some reason. 

![image](https://github.com/pybamm-team/PyBaMM/assets/74401230/7ca57f8b-02b9-4331-99f8-627730f5841f)
