### ISSUE TITLE
example notebook/tutorial: solving model & adding a solver

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#292]
Similar to #238

**Comment by tinosulzer** [comment]
@rtimms  would it be possible to implement mass matrix for the scikits ode solver (currently passed but not used)?

**Comment by rtimms** [comment]
cvode requires the send to be given explicitly in the form y’=f(t,y). would need to invert the mass matrix to use it with solver. I’m not sure how efficient that is, or whether we should encourage use of the scipy solver or gives the odes implicitly to IDA? I think sundials recommend ARKode for odes with a nonsingular mass matrix, but this isn’t in scikits

**Comment by tinosulzer** [comment]
Ok, I was thinking about the case where the mass matrix is tri-diagonal, but happy to just leave it out of the cvode solver and have it available if someone writes their own ODE solver and wants to use it

**Comment by rtimms** [comment]
One option would be to check if the mass matrix is the identity and then do nothing, otherwise invert and multiply rhs by the result (maybe with a warning). There is some discussion [here](https://stackoverflow.com/questions/21693613/is-it-possible-to-compute-an-inverse-of-sparse-matrix-in-python-as-fast-as-in-ma) about inverting sparse matrices with scipy
