### ISSUE TITLE
Some notebook lines are not being tested

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#3165]
As spotted in https://github.com/pybamm-team/PyBaMM/pull/3110#discussion_r1267382517, currently some lines in the notebooks are not tested. I don't know the reason, but I suspect that it is because in [this example](https://github.com/pybamm-team/PyBaMM/blob/v23.5/docs/source/examples/notebooks/creating_models/6-a-simple-SEI-model.ipynb) the following lines are not being tested
```python3
import ipywidgets as widgets
widgets.interact(plot, t=widgets.FloatSlider(min=0,max=solution.t[-1]*1e6,step=0.1,value=0));
```
so the error is not detected.

I am not sure if we were aware of this or not. I will work with @arjxn-py to fix that particular example, but this issue is to discuss if we need to fix the notebook testing.

**Comment by agriyakhetarpal** [comment]
There is also another issue with notebooks that use `ipywidgets` in specific (which was discussed with @tinosulzer and @rtimms in our last meeting)—apparently `nbsphinx` omits the slider on those notebooks when converting them to `.rst` format for rendering on the documentation, but it uses Pandoc to do it, so it could be out of our control.

I would propose we should use `importlib` and check for the use of `ipywidgets` (i.e., these lines) in any of the code blocks (which should be easy to add since we use `nbconvert` to parse the code portions and convert them to `.py` files) and check if the output of the slider is correct (I don't know how to do this)

**Comment by brosaplanella** [comment]
An option would be to use [nbmake](https://github.com/treebeardtech/nbmake) to test the notebooks, instead of what we currently do.

**Comment by arjxn-py** [comment]
> An option would be to use [nbmake](https://github.com/treebeardtech/nbmake) to test the notebooks, instead of what we currently do.

[nbmake](https://github.com/treebeardtech/nbmake) looks promising.
I had also went through one - [nbval](https://github.com/computationalmodelling/nbval)
