### ISSUE TITLE
[Bug]: windows wheels not being built

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#3431]
### PyBaMM Version

develop

### Python Version

all

### Describe the bug

from Saransh Chopra (@Saransh-cpp): "MacOS wheels are okay. Linux wheels have been fixed by dropping i686 support, and SuiteSparse’s version has been bumped to 6.0.3 for building the wheels. Windows wheels are still failing - SUNDIALS (and probably Casadi) should be bumped in their respective registries (might or might not solve the build error)

### Steps to Reproduce

build wheels github action

### Relevant log output

```shell
none
```

**Comment by jsbrittain** [comment]
@martinjrobins very surprised by this as i thought variable length arrays had been supported for a while. having said that I just had a quick google and there is some mention of them not being part of the standard and as such not compiling on msvc. solutions are dynamic allocation with `new` or, as you say, refactoring to `std::vector`. As a side note, if there are cascading issues and this continues to cause problems and needs to be resolved quickly, then I'm almost completely certain that our solver never uses this code branch - we use CSC_MAT, with the CSR_MAT block only there to support the SUNDIALS CUDA solver which we don't have a working implementation for - so that whole branch could be commented or throw a not implemented exception if needed (hopefully we won't have to resort to that, but its worth mentioning). I don't normally use vscode, but will see if I can recreate the error (mainly for consistency going forwards).
