### ISSUE TITLE
[Bug]: non-required dependency `typing_extensions` is imported by default

### ISSUE THREAD

**Issue by arjxn-py** [pybamm-team/PyBaMM#3836]
### PyBaMM Version

24.1

### Python Version

3.8-3.12

### Describe the bug

There might be some instance in #3578 where non required dependency has been imported by default, which is causing failure, [related build logs](https://github.com/arjxn-py/PyBaMM/actions/runs/8032837736/job/21942676799). 

### Steps to Reproduce

* try installing latest built wheels on develop
* do `import pybamm`

**Comment by agriyakhetarpal** [comment]
Note: this happens with `sympy` as well

**Comment by agriyakhetarpal** [comment]
Also, it's weird that the tests for `have_optional_dependency` in `test_util.py` didn't catch `typing-extensions` and `sympy` – is this because we are not mocking all of the optional dependencies inside that test case? IMO, we should mock all of the optional dependencies to ensure that this problem doesn't get repeated in the future.

**Comment by arjxn-py** [comment]
I tried importing `typing-extensions` as an optional dependency but it is being imported outside a function in `unit/type_definitions.py` and then those types in `type_definitions.py` are then being imported and used as args at several instances, which is making `have_optional_dependency` unable to resolve the issue.

**Comment by arjxn-py** [comment]
How about we consider making `typing-extensions` a required dependency?
