### ISSUE TITLE
Documentation fails to build in CI

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#4082]
The documentation fails to build in the CI for Ubuntu and Python 3.12: https://github.com/pybamm-team/PyBaMM/actions/runs/9056632702/job/24879466141

Not sure what the issue is, but seems to be failing repeatedly, while working for other Python versions.

**Comment by agriyakhetarpal** [comment]
Ah, looks like we will still require the `session.install("setuptools")` hack for `pybtex` to work on Python 3.12. We have not been testing the documentation builds with 3.12, but with 3.11, rather, in the regular PR tests. As an aside, we should look to revise the workflows so that the nightly tests also run in parallel rather than running the different sessions sequentially.

**Comment by cringeyburger** [comment]
Hi! I would like to work on this issue

**Comment by arjxn-py** [comment]
Assigned this to you @cringeyburger, feel free to let know in case you'd want to discuss something related.

**Comment by cringeyburger** [comment]
From what I understand, I need to add a temporary fix to `noxfile` by adding `session.install("setuptools", silent=False)`?

**Comment by agriyakhetarpal** [comment]
> From what I understand, I need to add a temporary fix to `noxfile` by adding `session.install("setuptools", silent=False)`?

In the docs session, yes, that – and then parallelise the scheduled tests to resemble the `test_on_push.yml` job minus all of the caching stuff.
