### ISSUE TITLE
Lead-acid discharge plots

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#410]
Make script to produce discharge plots for the lead-acid papers

**Comment by tinosulzer** [comment]
Have finished this, but now not sure if it's better to do this in the main PyBaMM repo, or in my own fork. What do you reckon @martinjrobins ?

**Comment by martinjrobins** [comment]
I was thinking we should have a `papers` directory somewhere, where we can put scripts relevant to papers using pybamm. Ideally, these would be tested along with everything else, so that the research from the papers is always reproducible. Presumably something like this would live there, in the main repo?
