### ISSUE TITLE
Rename `set_events`

### ISSUE THREAD

**Issue by MehrdadBabazadeh** [pybamm-team/PyBaMM#4266]
As discussed in the PR #4254, `set_event` should be renamed because of misleading.

              This adds a side effect to what would be expected to be a simple setter. At minimum it should be changed to `append_events()` or `add_events()`. Was there an actual bug that this was fixing or just not sure if it would cause issues?

_Originally posted by @kratman in https://github.com/pybamm-team/PyBaMM/pull/4254#discussion_r1672332716_

**Comment by brosaplanella** [comment]
I would also vote for using a dictionary instead of a list, so it is easier to access a specific event in case the user wants to modify in.

**Comment by kratman** [comment]
> I would also vote for using a dictionary instead of a list, so it is easier to access a specific event in case the user wants to modify in.

The one advantage of a list over a dictionary is the ordering in a list. So if we are appending to a list then the events are in some order. We can use an "OrderedDict" object to get both

**Comment by valentinsulzer** [comment]
Ordering is not super important, and Python's dict is an `OrderedDict` since Python 3.6

**Comment by medha-14** [comment]
The changes are to be made in `ocv_element.py `and `diffusion_element.py`  or only one of them as I see the issue to be that the `set_events` method is appending the  events rather than  replacing it.
Shall I make a PR for the same?

**Comment by agriyakhetarpal** [comment]
Hi @medha-14, let's wait for a few days for a response from @MehrdadBabazadeh since they are assigned to this issue. Otherwise, please feel free to take it up!

**Comment by kratman** [comment]
@medha-14, @agriyakhetarpal This ticket has been open for a while, and can safely be taken over.

@medha-14 The core issue is that all versions of `set_events` are not actually setting the events, but rather appending to the existing list. The smallest change for this would be to rename the function to something like `add_events_from` so that the code would clearly read along the lines of `model.add_events_from(new_events)`. This makes it far more clear what the function is doing, but keep in mind that `set_events` is not used only in the `ocv_element.py` and `diffusion_element.py` files. You need to change ALL of the usages, not just the ones in those two files.

I think things like switching it to a dictionary can come afterwards. Lets get the rename done first since that does not require too many other changes

**Comment by medha-14** [comment]
Thank you for the response, I have made the necessary changes and put them up for review.
