### ISSUE TITLE
How to install JellyBamm package

### ISSUE THREAD

**Issue by Santiagopeacely** [pybamm-team/PyBaMM#4299]
Pybamm is a very useful and effective lithium battery pack. I want to explore the spatial temperature distribution of cylindrical batteries, but I encountered some problems when installing JellyBamm. I don't know how to install it. I hope you can give me some help with installation. Thank you！

**Comment by agriyakhetarpal** [comment]
Currently JellyBaMM is not distributed through PyPI, so you shall have to install from source. There are instructions in the GitHub repository for JellyBaMM: https://github.com/TomTranter/JellyBaMM. You may also also try the

```
pip install git+https://github.com/TomTranter/JellyBaMM.git
```

command to let `pip` install it from the repository instead of having to clone it.
