### ISSUE TITLE
[Bug]: Variables names missing from plot

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#4620]
### PyBaMM Version

24.11.1

### Python Version

3.11

### Describe the bug

Dynamic plot has no variable labels and shows the legend entries as `t=0.00h` for all plots

![Image](https://github.com/user-attachments/assets/4ab94412-5ffd-4298-8c7a-fa93a5c76e35)

### Steps to Reproduce

```python3
import pybamm

model = pybamm.lithium_ion.SPM()

sim = pybamm.Simulation(model)
sim.solve([0, 3600])


sim.plot()
```

### Relevant log output

```shell

```

**Comment by rtimms** [comment]
From https://github.com/pybamm-team/PyBaMM/pull/4529

**Comment by kratman** [comment]
@rtimms Sorry missed in the review

**Comment by agriyakhetarpal** [comment]
cc: @medha-14, this might be worth a look!

**Comment by brosaplanella** [comment]
Another issue that I believe is related: when plotting 2D variables the colourbar range is wrong:

## 24.9
![Image](https://github.com/user-attachments/assets/31be8b94-3128-4fdd-8886-a936f8dd036b)

## 24.11
![Image](https://github.com/user-attachments/assets/d807d9f8-2ba9-4751-8396-13e027d1c62f)

**Comment by brosaplanella** [comment]
Digging a bit deeper, there also some inconsistencies when plotting multiple solutions in one plot. Given that there are multiple issues to fix (basically the issue is a lot harder than I anticipated in #4271 😅) and plotting is quite a major feature, I suggest reverting #4529 and making a minor release. We can then address this for the next major release.

![Image](https://github.com/user-attachments/assets/9aa0319c-f71b-4489-add9-3ad444a46f5d)
