### ISSUE TITLE
Add active and inactive material volume fractions

### ISSUE THREAD

**Issue by ferranbrosa** [pybamm-team/PyBaMM#579]
**Summary**
In the current definition of the parameters the microstructure is defined by the porosity. I assume this means that the rest of the volume fraction is assumed to be active material. It would be interesting to split the volume fractions into electrolyte (i.e. porosity), active material and inactive material.

 **Motivation**
In some cases the conductive filler in the electrode can make up to 10% of the volume so that has an impact on the amount of active material to consider in the model.

**Comment by tinosulzer** [comment]
> I assume this means that the rest of the volume fraction is assumed to be active material

Yes, in the electrode submodels the electrode volume fraction is just defined as `1-eps` (e.g. `sigma_eff * (1 - eps) ** bruggeman`

**Comment by tinosulzer** [comment]
Need this now, @ferranbrosa have you started on this?

**Comment by ferranbrosa** [comment]
I haven't, sorry! Go ahead with it.

**Comment by tinosulzer** [comment]
No problem.
What is the symbol for active material volume fraction?
Also, renaming everything from "porosity" to "electrolyte volume fraction" is a bit of a pain but can be done, do you think this is necessary? Otherwise, we have "porosity" which refers to electrolyte volume fraction, and "active material volume fraction" which refers to electrode volume fraction

**Comment by ferranbrosa** [comment]
Whatever you prefer for the notation, I have seen both terms used.
