### ISSUE TITLE
Improve interface for post-processed variables, including exporting

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#695]
**Summary**
 Add functionality to simulation class to post-process and export variables

 **Motivation**
Allow users to export variables to csv, matlab, etc for visualisation

**Comment by TomTranter** [comment]
How would this handle the various spatial and temporal differences in the data? As there are many permutations might be better just to leave this in the users hands.

**Comment by TomTranter** [comment]
After our conversation about this - I think it would be really useful to group the variables into domains so that they can all be visualized in the same way. If you run the following on a 1 plus 1D it fails on about half the variables
pybamm.post_process_variables(variables=spm.model.variables, t_sol=spm.solution.t, u_sol=spm.solution.y, mesh=spm.mesh)
maybe the post_process_variables and any new functions could accept a domain argument and only spit back the ones defined on that domain. Or if no domain is specified is could return a dict of dicts with the domain as the key on the first level

**Comment by rtimms** [comment]
following on from that, it would be really great in Nplus1 to be able to visualize or create post process variables for the 1D model at a given y,z coordinate. But maybe this is more difficult than just improving how processed vars deals with higher-D variables...

**Comment by tinosulzer** [comment]
ProcessedVariable is a hacky mess atm so I am very happy for you to completely overhaul it if you have clear ideas how to do it. There's no support for 4D objects (t+r+x+z) atm hence why 1 plus 1D SPM fails.
