### ISSUE TITLE
Pass options to spatial methods

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#708]
**Summary**
Allow more specific versions of the FiniteVolume method to be used (e.g. with linear extrapolation or quadratic extrapolation, use arithmetic mean or harmonic mean when shifting from nodes to edges)

Should we:
1. Create a new inherited class for each option (e.g. `FiniteVolumeLinearExtrapolation`) etc
2. Allow for such options to be applied to specific symbols (e.g. `pybamm.surf(c_s, "linear")`) 
3. Create a generator class of spatial methods and allow for a dictionary of `options` to be passed to the spatial method
4. change the `__init__` of spatial methods so that only a dict of `options` are taken in upon initialisation and then when the object passed to `Discretisation` we call a second `set_up` function that has the same functionality as the current `__init__` method.

I am most in favor of 4. but 2. probably requires the least changes to the code. 

Thoughts?

 **Motivation**
Following from discussion in pull request #707 .

**Comment by tinosulzer** [comment]
Right, I see that issue that there might be a few different options which makes 1 a bad idea. Agreed that 4 sounds like the best option. It should only require a change to one line in discretisation, and a few relevant tests? We could even make `mesh` an optional input to `__init__`, (`__init__` calls `set_up` directly if a mesh is provided) so that existing functionality still works, but this might be confusing
