### ISSUE TITLE
ParameterValues inherit from dict

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#889]
If we make ParameterValues inherit from dict, then we can tab complete to find parameter values within ipython (and so Jupyter notebooks). N.B tab complete already works with model.variables in ipython and jupyter notebooks

**Comment by tinosulzer** [comment]
I removed the inheritance from dict because it was causing problems with pickle and I read somewhere that it was better to define your own `__getitem__`, etc anyway. Happy to go back to dict if you can get it passing all the tests. Otherwise, it might be easier to just add a `__dir__` or `_ipython_key_completions_()` method as suggested [here](https://ipython.readthedocs.io/en/stable/config/integrating.html)

**Comment by Scottmar93** [comment]
Ah cheers, will look into the key completions :) thought this was just a simple thing we missed.
