### ISSUE TITLE
Loading simulations

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#960]
When loading a simulation using `sim.load("something.p")` I get the error:
```
No module named 'graphite_diffusivity_Kim2011'
```
But if I add the lines:
```
chemistry = pybamm.parameter_sets.NCA_Kim2011
parameter_values = pybamm.ParameterValues(chemistry=chemistry)
```
before loading the simulation, it loads and works fine. 

Can anyone else can reproduce this? Might just be an issue with my own python setup.

**Comment by rtimms** [comment]
yeah I get the same. looks like #792 is related.

also note that if you try to save after plotting you get 
```  
File "/home/user/Documents/PyBaMM/pybamm/simulation.py", line 748, in save
    pickle.dump(self, f, pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _tkinter.tkapp objects
```
might be worth fixing this too (presumably you can just remove all the plot stuff before saving)

**Comment by tinosulzer** [comment]
Yeah I get this issue too. Also get it if trying to save a simulation where one of the parameter functions has been defined locally.
It's definitely a problem with loading modules but I have no idea how to fix it.

**Comment by tinosulzer** [comment]
It looks like the problem is that the path to a particular function (e.g. graphite_diffusivity_Kim2011) is not added to the sys path by default. Some possible workarounds:

1. (preferred but can't find how to do this) redefine the function locally inside `ParameterValues`. If not possible with python then maybe we could do it by creating some expression tree.
2. Automatically import functions defined in inputs/parameters to the pybamm package. This isn't ideal as it doesn't deal with the case where a function has been defined locally
3. Use something other than pickle that doesn't have this issue

**Comment by priyanshuone6** [comment]
@tlestang Are you working on this issue? Can I work on this

**Comment by tlestang** [comment]
No I'm not, feel free to work on this
