### ISSUE TITLE
Casadi extrapolate warning/error

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#976]
When Casadi extrapolates you get errors like
```
At t = 0.300171, , mxstep steps taken before reaching tout.
psetup failed: .../casadi/interfaces/sundials/idas_interface.cpp:830: Linear solve failed
psetup failed: .../casadi/interfaces/sundials/idas_interface.cpp:830: Linear solve failed
psetup failed: .../casadi/interfaces/sundials/idas_interface.cpp:830: Linear solve failed
psetup failed: .../casadi/interfaces/sundials/idas_interface.cpp:830: Linear solve failed
```
which are hard to trace back to the interpolant. It would be useful to throw a warning/error when this happens which is more insightful.

**Comment by tinosulzer** [comment]
It's not possible to do this directly as we don't have control over the casadi objects.
But we could add a new type of event to the model, which automatically gets added when an interpolant is added to the model?

**Comment by ferranbrosa** [comment]
You mean an event in the solver?

**Comment by tinosulzer** [comment]
Yes, events are stored in the model then used by the solver

**Comment by tinosulzer** [comment]
Can you create a branch and add a test where it fails?

**Comment by ferranbrosa** [comment]
Looking into this issue at the moment and trying to recall what we discussed. The issue is that the Casadi interpolant throws NaNs when it extrapolates (side note here: the default interpolant behaviour is to extrapolate, is Casadi ignoring it or is it taking `extrapolate=False`?).

Adding events would be an easy fix (we then would know which interpolant broke and on which limit). But what do we want to do then? Stop the simulation and just tell the user that this was the issue? Throw an error? Throw a warning?
